### ISSUE TITLE
Do not use LZMA end marker

### ISSUE THREAD

**Issue by n1ko-w1ll** [Danny02/JOpenCTM#4]
Hi Danny,

thanks for your work porting the original C/C++ implementation to Java. It took me a while to find out why files written by JOpenCTM could not be opened by some OpenCTM viewer applications. The C/C++ implementation does not write end markers to the LZMA output as the original data size plus the packed size is known. After changing the setEndMarkerMode to false, the written files can be opened by other tools.

I'll send a pull request soon.

kind regards
Niko

**Comment by Danny02** [comment]
Thx for the feedback. This change should be available shortly as version 1.4.1
